[server]
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = true
enableXsrfProtection = false
allowRunOnSave = false

[browser]
gatherUsageStats = false

[server.fileWatcherType]
# Disable file watcher in production
type = "none"
