[server]
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
allowRunOnSave = false
baseUrlPath = ""

[browser]
gatherUsageStats = false

[server.fileWatcherType]
# Disable file watcher in production
type = "none"
